### ISSUE TITLE
Proposal -:- Assault Rigs

### ISSUE THREAD

**Issue by cheznewa** [Pixelsuft/dosbox-demos#1]
Hi/Hello It's Possible To Add A Game Is Assault Rigs?
The Source ::: https://www.myabandonware.com/game/assault-rigs-2nz

Newa Our Master.

**Comment by Pixelsuft** [comment]
I've added that game: https://pixelsuft.github.io/dosbox-demos/assaultrigs/
But perfomance isn't good

**Comment by cheznewa** [comment]
Thank You!
